In [2]:
import pandas as pd

In [3]:
#reading 1 csv file from the website 
df_premier25 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [4]:
#showing dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99
9,E0,18/08/2025,20:00,Leeds,Everton,1,0,H,0,0,...,2.05,1.80,2.02,1.90,2.05,1.86,1.91,1.78,2.14,1.86
10,E0,22/08/2025,20:00,West Ham,Chelsea,1,5,A,1,3,...,1.83,2.03,2.06,1.87,1.95,2.03,1.85,1.89,2.02,1.96
11,E0,23/08/2025,12:30,Man City,Tottenham,0,2,A,0,2,...,1.87,1.87,1.83,2.11,1.87,2.09,1.81,1.95,1.94,2.04
12,E0,23/08/2025,15:00,Bournemouth,Wolves,1,0,H,1,0,...,2.05,1.80,2.05,1.88,2.07,1.81,1.99,1.76,2.17,1.83
13,E0,23/08/2025,15:00,Brentford,Aston Villa,1,0,H,1,0,...,2.03,1.83,1.94,1.98,2.03,1.93,1.92,1.78,2.04,1.93
14,E0,23/08/2025,15:00,Burnley,Sunderland,2,0,H,0,0,...,2.00,1.85,2.00,1.93,2.02,1.85,1.94,1.80,2.09,1.90
15,E0,23/08/2025,17:30,Arsenal,Leeds,5,0,H,2,0,...,2.00,1.85,2.04,1.88,2.00,1.91,1.91,1.85,2.06,1.92
16,E0,24/08/2025,14:00,Crystal Palace,Nott'm Forest,1,1,D,1,0,...,1.99,1.74,2.10,1.84,2.04,1.81,1.95,1.77,2.13,1.88
17,E0,24/08/2025,14:00,Everton,Brighton,2,0,H,1,0,...,2.04,1.72,2.24,1.73,2.10,1.76,2.06,1.72,2.24,1.80
18,E0,24/08/2025,16:30,Fulham,Man United,1,1,D,0,0,...,2.03,1.83,2.04,1.88,2.04,1.83,2.01,1.71,2.13,1.87
19,E0,25/08/2025,20:00,Newcastle,Liverpool,2,3,A,0,1,...,1.83,2.03,1.87,2.07,1.85,2.03,1.83,1.88,1.93,2.06

In [5]:
#rename columns
df_premier25.rename(columns={'FTHG' : 'home_goals', 'FTAG' : 'away_goals'},inplace=True)

In [6]:
#show dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99
9,E0,18/08/2025,20:00,Leeds,Everton,1,0,H,0,0,...,2.05,1.80,2.02,1.90,2.05,1.86,1.91,1.78,2.14,1.86
10,E0,22/08/2025,20:00,West Ham,Chelsea,1,5,A,1,3,...,1.83,2.03,2.06,1.87,1.95,2.03,1.85,1.89,2.02,1.96
11,E0,23/08/2025,12:30,Man City,Tottenham,0,2,A,0,2,...,1.87,1.87,1.83,2.11,1.87,2.09,1.81,1.95,1.94,2.04
12,E0,23/08/2025,15:00,Bournemouth,Wolves,1,0,H,1,0,...,2.05,1.80,2.05,1.88,2.07,1.81,1.99,1.76,2.17,1.83
13,E0,23/08/2025,15:00,Brentford,Aston Villa,1,0,H,1,0,...,2.03,1.83,1.94,1.98,2.03,1.93,1.92,1.78,2.04,1.93
14,E0,23/08/2025,15:00,Burnley,Sunderland,2,0,H,0,0,...,2.00,1.85,2.00,1.93,2.02,1.85,1.94,1.80,2.09,1.90
15,E0,23/08/2025,17:30,Arsenal,Leeds,5,0,H,2,0,...,2.00,1.85,2.04,1.88,2.00,1.91,1.91,1.85,2.06,1.92
16,E0,24/08/2025,14:00,Crystal Palace,Nott'm Forest,1,1,D,1,0,...,1.99,1.74,2.10,1.84,2.04,1.81,1.95,1.77,2.13,1.88
17,E0,24/08/2025,14:00,Everton,Brighton,2,0,H,1,0,...,2.04,1.72,2.24,1.73,2.10,1.76,2.06,1.72,2.24,1.80
18,E0,24/08/2025,16:30,Fulham,Man United,1,1,D,0,0,...,2.03,1.83,2.04,1.88,2.04,1.83,2.01,1.71,2.13,1.87
19,E0,25/08/2025,20:00,Newcastle,Liverpool,2,3,A,0,1,...,1.83,2.03,1.87,2.07,1.85,2.03,1.83,1.88,1.93,2.06

https://www.football-data.co.uk/mmz4281/2526/E0.csv

In [7]:
#link structure
"https://www.football-data.co.uk" + "mmmz4281" + "2526" + "E0" + "csv"

'https://www.football-data.co.ukmmmz42812526E0csv'

In [8]:
#Root Variable 
root = "https://www.football-data.co.uk/mmmz4281/"

In [ ]:
#creating list of leagues 
leagues = ['E0','E1','E2','E3','EC']
#Creating empty list to store populated league data
frames = []

#looping through leagues, read multiple csv and append it into a list 
for league in leagues:
    df = pd.read_csv(root + '2526' + '/' + league + '.csv')
    frames.append(df)

In [10]:
#length of frames
len(frames)

5

In [21]:
#show 1st,2nd,3rd element

In [14]:
#Creating League List
leagues = ['E0','E1','E2']
#Create Empty List to store data
frames = []

for league in leagues:
    for season in range(15,26):
        df = pd.read_csv(root + str(season) + str(season + 1) + '/' + league + '.csv')
        df.insert(1,'Season',str(season))
        frames.append(df)

In [15]:
len(frames)

33

In [19]:
dict_countries = {
    'Spanish La Liga': 'SP1',
    'German Bundesliga': 'D1',
    'English Premier League': 'E0',
    'Scottish Premier League': 'SC0',
    'Portuguese Liga': 'P1',
    'Italian Serie A': 'I1',
    'French Ligue 1': 'F1',
}

In [20]:
dict_countries['Spanish La Liga']

'SP1'

In [24]:
dict_historical_data = {}

for league in dict_countries:
    frames = []
    for season in range(20,26):
        df = pd.read_csv(root + str(season) + str(season + 1) + '/' + dict_countries[league] + '.csv')
        df.insert(1,'Season',str(season))
        frames.append(df)
    df_concat =  pd.concat(frames)
    dict_historical_data[league] = df_concat

In [28]:
dict_historical_data['Spanish La Liga']

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,20,12/09/2020,15:00,Eibar,Celta,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,20,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,20,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,20,13/09/2020,13:00,Alaves,Betis,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,20,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,SP1,25,24/08/2025,18:30,Villarreal,Girona,5,0,H,4,...,7.00,1.45,4.50,6.5,1.48,4.50,6.50,1.48,4.4,6.50
17,SP1,25,24/08/2025,20:30,Oviedo,Real Madrid,0,3,A,0,...,1.26,10.50,5.25,1.3,10.00,5.25,1.33,9.50,5.0,1.33
18,SP1,25,25/08/2025,18:30,Ath Bilbao,Vallecano,1,0,H,0,...,5.00,1.73,3.60,5.0,1.75,3.50,5.00,1.73,3.5,5.00
19,SP1,25,25/08/2025,20:30,Sevilla,Getafe,1,2,A,1,...,4.00,2.05,2.90,4.4,2.05,3.00,4.20,2.05,3.0,4.00
20,SP1,25,27/08/2025,20:00,Celta,Betis,1,1,D,0,...,2.90,2.30,3.60,2.9,2.30,3.50,3.00,2.25,3.4,3.00